# Copyright 2026 QUBIQ (https://www.qubiq.es)
# License OPL-1.0

import json
import queue
import threading
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer

TRACE_HISTORY = []
TRACE_CLIENTS = []
TRACE_LOCK = threading.Lock()
SERVER_STARTED = False
MAX_HISTORY_EVENTS = 20000


def push_trace_event(event):
    """Store a trace event and broadcast it to all connected browser clients.

    The event is appended to the in-memory history so it remains visible after a
    page refresh. It is also sent to every active Server-Sent Events client.

    Args:
        event (dict): Structured trace event generated by the performance
            decorator.
    """

    with TRACE_LOCK:
        TRACE_HISTORY.append(event)

        if len(TRACE_HISTORY) > MAX_HISTORY_EVENTS:
            del TRACE_HISTORY[: len(TRACE_HISTORY) - MAX_HISTORY_EVENTS]

        clients = list(TRACE_CLIENTS)

    for client_queue in clients:
        try:
            client_queue.put_nowait(event)
        except queue.Full:
            pass


class TraceHTTPServer(ThreadingHTTPServer):
    """Threaded HTTP server used to serve the trace dashboard.

    ``daemon_threads`` is enabled so client handler threads do not block the
    Odoo process from shutting down.
    """

    daemon_threads = True


class TraceRequestHandler(BaseHTTPRequestHandler):
    """HTTP request handler for the local performance trace dashboard.

    It serves the HTML interface, exposes the trace history as JSON, streams
    real-time trace events through Server-Sent Events, and allows clearing the
    in-memory history.
    """

    def log_message(self, format, *args):
        """Disable default HTTP access logging.

        This keeps the Odoo console clean while the trace dashboard is being used.
        """

        return

    def do_GET(self):
        """Route incoming GET requests to the matching dashboard endpoint.

        Supported endpoints are:

        - ``/``: HTML dashboard.
        - ``/events``: Server-Sent Events stream.
        - ``/history``: JSON history of stored trace events.
        - ``/clear``: Clear the in-memory trace history.
        """

        if self.path == "/":
            self._send_index()
        elif self.path == "/events":
            self._send_events()
        elif self.path == "/history":
            self._send_history()
        elif self.path == "/clear":
            self._clear_history()
        else:
            self.send_response(404)
            self.end_headers()

    def _send_history(self):
        """Return the current trace history as JSON.

        The history is read under a lock to avoid concurrent modifications while
        connected clients are receiving new events.
        """

        with TRACE_LOCK:
            payload = json.dumps(TRACE_HISTORY)

        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Cache-Control", "no-cache")
        self.end_headers()
        self.wfile.write(payload.encode("utf-8"))

    def _clear_history(self):
        """Clear the in-memory trace history.

        This only affects the current Odoo process memory. It does not delete any
        database record because trace events are intentionally not persisted.
        """

        with TRACE_LOCK:
            TRACE_HISTORY.clear()

        self.send_response(200)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.end_headers()
        self.wfile.write(b'{"status": "ok"}')

    def _send_index(self):
        """Serve the HTML dashboard used to visualize trace events.

        The page loads previous events from ``/history`` and subscribes to ``/events``
        to receive new trace events in real time.
        """

        html = r"""<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>QUBIQ Performance Trace</title>
    <style>
        :root {
            --bg:     #0f172a;
            --panel:  #020617;
            --border: #334155;
            --text:   #e5e7eb;
            --muted:  #94a3b8;
            --blue:   #60a5fa;
            --green:  #22c55e;
            --yellow: #eab308;
            --orange: #f97316;
            --red:    #ef4444;
        }
        *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
        body {
            background: var(--bg);
            color: var(--text);
            font-family: Menlo, Consolas, 'Courier New', monospace;
            font-size: 13px;
            overflow-x: hidden;
        }
        header {
            position: sticky; top: 0; z-index: 10;
            padding: 12px 20px;
            background: var(--panel);
            border-bottom: 1px solid var(--border);
        }
        h1 { margin: 0 0 8px; color: #93c5fd; font-size: 20px; letter-spacing: -.3px; }
        .toolbar { display: flex; gap: 8px; flex-wrap: wrap; align-items: center; }
        .badge {
            padding: 4px 10px; border-radius: 999px;
            background: #1e293b; border: 1px solid var(--border);
            font-size: 12px; color: var(--muted);
        }
        .badge b { color: var(--text); }
        .btn {
            padding: 5px 12px; border-radius: 6px; border: 0;
            background: #2563eb; color: #fff;
            font-family: inherit; font-size: 12px; cursor: pointer;
        }
        .btn:hover { background: #1d4ed8; }
        .btn-clear { background: #334155; }
        .btn-clear:hover { background: #475569; }

        /* ── log area ── */
        #log { padding: 12px 16px 80px; }
        .empty { color: var(--muted); padding: 20px 0; }

        /* ── rows ── */
        .line {
            display: grid;
            grid-template-columns: 90px 80px 64px 1fr;
            gap: 8px;
            align-items: center;
            padding: 4px 8px;
            margin-bottom: 2px;
            border-left: 3px solid var(--border);
            border-radius: 0 5px 5px 0;
        }
        .line:hover { background: rgba(255,255,255,0.04); }

        .line.root    { background: rgba(37,99,235,.18); border-left-color: var(--blue); font-weight: 600; }
        .line.fast    { border-left-color: var(--green); }
        .line.medium  { border-left-color: var(--yellow); background: rgba(234,179,8,.06); }
        .line.slow    { border-left-color: var(--orange); background: rgba(249,115,22,.09); }
        .line.vslow   { border-left-color: var(--red); background: rgba(239,68,68,.14); font-weight: 600; }
        .line.error   { border-left-color: var(--red); background: rgba(127,29,29,.50); color: #fecaca; font-weight: 600; }

        /* ── pill ── */
        .pill {
            text-align: center; font-size: 10px; font-weight: 700;
            padding: 2px 6px; border-radius: 999px; border: 1px solid transparent;
            white-space: nowrap;
        }
        .pill.p-root-s { color: #bfdbfe; border-color: rgba(96,165,250,.5); background: rgba(37,99,235,.35); }
        .pill.p-root-e { color: #bfdbfe; border-color: rgba(96,165,250,.5); background: rgba(37,99,235,.35); }
        .pill.p-start  { color: var(--blue);  border-color: rgba(96,165,250,.4); background: rgba(96,165,250,.10); }
        .pill.p-end    { color: var(--green); border-color: rgba(34,197,94,.4);  background: rgba(34,197,94,.10); }
        .pill.p-error  { color: #fff;         border-color: rgba(239,68,68,.7);  background: rgba(239,68,68,.35); }

        /* ── duration ── */
        .dur { text-align: right; font-weight: 700; font-size: 12px; }
        .dur.d-root   { color: var(--blue); }
        .dur.d-fast   { color: var(--green); }
        .dur.d-medium { color: var(--yellow); }
        .dur.d-slow   { color: var(--orange); }
        .dur.d-vslow  { color: var(--red); }
        .dur.d-none   { color: var(--muted); }

        .depth-col { color: var(--muted); font-size: 10px; text-align: right; }

        /* ── content ── */
        .content { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
        .c-indent  { color: #334155; }
        .c-path    { color: #a5b4fc; }
        .c-func    { color: #f8fafc; font-weight: 700; }
        .c-root-fn { color: #93c5fd; font-weight: 700; }
        .c-msg     { color: var(--muted); }

        /* ── filter bar ── */
        .filter-bar { display: flex; gap: 6px; align-items: center; margin-top: 8px; }
        .filter-bar input {
            background: #1e293b; border: 1px solid var(--border); color: var(--text);
            border-radius: 6px; padding: 4px 10px; font-family: inherit; font-size: 12px;
            width: 220px; outline: none;
        }
        .filter-bar input:focus { border-color: #3b82f6; }
        .filter-bar label { font-size: 11px; color: var(--muted); display: flex; gap: 4px; align-items: center; cursor: pointer; }
        .filter-bar input[type=checkbox] { accent-color: var(--blue); width: 13px; height: 13px; }
    </style>
</head>
<body>
<header>
    <h1>QUBIQ Performance Trace</h1>
    <div class="toolbar">
        <span class="badge">Events <b id="cnt">0</b></span>
        <span class="badge">Slow <b id="sl">0</b></span>
        <span class="badge">Very slow <b id="vsl">0</b></span>
        <span class="badge">Last root <b id="lr">—</b></span>
        <button class="btn btn-clear" onclick="clearTrace()">Clear</button>
    </div>
    <div class="filter-bar">
        <input id="filterInput" type="text" placeholder="Filter by function or path…" oninput="applyFilter()"/>
        <label><input type="checkbox" id="onlySlow" onchange="applyFilter()"/> Solo slow/very-slow</label>
        <label><input type="checkbox" id="onlyEnd"  onchange="applyFilter()"/> Solo END</label>
    </div>
</header>

<main id="log">
    <div class="empty">Waiting for events from the tracing server…</div>
</main>

<script>
const logEl   = document.getElementById('log');
const cntEl   = document.getElementById('cnt');
const slEl    = document.getElementById('sl');
const vslEl   = document.getElementById('vsl');
const lrEl    = document.getElementById('lr');
const fInput  = document.getElementById('filterInput');
const chkSlow = document.getElementById('onlySlow');
const chkEnd  = document.getElementById('onlyEnd');

let cnt = 0, slow = 0, vslow = 0;

// ── helpers ──────────────────────────────────────────────────────────────────

function esc(v) {
    return String(v ?? '')
        .replace(/&/g,'&amp;').replace(/</g,'&lt;')
        .replace(/>/g,'&gt;').replace(/"/g,'&quot;');
}

function compactPath(p) {
    if (!p) return '';
    return p
        .replace('/opt/odoo/auto/addons/',       'auto/')
        .replace('/opt/odoo/custom/src/odoo/odoo/', 'odoo/')
        .replace('/opt/odoo/custom/src/private/', 'private/')
        .replace('/opt/odoo/custom/src/',         'custom/');
}

function classify(elapsed, type) {
    if (type === 'error')                            return 'error';
    if (type === 'root_start' || type === 'root_end') return 'root';
    if (!elapsed || elapsed < 0.2)                  return 'fast';
    if (elapsed < 1)                                return 'medium';
    if (elapsed < 5)                                return 'slow';
    return 'vslow';
}

function durClass(cls) {
    return { root:'d-root', fast:'d-fast', medium:'d-medium', slow:'d-slow', vslow:'d-vslow' }[cls] ?? 'd-none';
}

function treePrefix(depth, type) {
    if (!depth || type === 'root_start' || type === 'root_end') return '';
    return '│   '.repeat(Math.max(depth - 1, 0)) + '├── ';
}

// ── render ───────────────────────────────────────────────────────────────────

function renderEvent(data) {
    const empty = logEl.querySelector('.empty');
    if (empty) empty.remove();

    cnt++;
    cntEl.textContent = cnt;

    const type    = data.event_type ?? '';
    const elapsed = data.elapsed   ?? 0;
    const depth   = data.depth     ?? 0;
    const cls     = classify(elapsed, type);

    if (cls === 'slow')  { slow++;  slEl.textContent  = slow; }
    if (cls === 'vslow') { vslow++; vslEl.textContent = vslow; }
    if (type === 'root_start' || type === 'root_end') lrEl.textContent = data.function ?? '—';

    // ── pill ──
    const pillCls = {
        root_start: 'p-root-s', root_end: 'p-root-e',
        start: 'p-start', end: 'p-end', error: 'p-error',
    }[type] ?? 'p-start';

    const pillText = {
        root_start: 'ROOT ▶', root_end: 'ROOT ■',
        start: 'START', end: 'END', error: 'ERROR',
    }[type] ?? type.toUpperCase();

    // ── content ──
    const isRoot   = type === 'root_start' || type === 'root_end';
    const prefix   = treePrefix(depth, type);
    const path     = compactPath(data.filename ?? '');
    const fn       = data.function ?? '';
    const msg      = data.message  ?? '';
    const showMsg  = msg && msg !== 'START' && msg !== 'END';

    const contentHTML = isRoot
        ? `<span class="c-root-fn">${esc(fn)}</span>${showMsg ? ` <span class="c-msg">— ${esc(msg)}</span>` : ''}`
        : `<span class="c-indent">${esc(prefix)}</span>${path ? `<span class="c-path">${esc(path)}</span><span class="c-msg">:</span>` : ''}<span class="c-func">${esc(fn)}</span>${showMsg ? ` <span class="c-msg">— ${esc(msg)}</span>` : ''}`;

    // ── assemble ──
    const row = document.createElement('div');
    row.className = 'line ' + cls;
    // store searchable text for filtering
    row.dataset.search = (path + ' ' + fn + ' ' + msg).toLowerCase();
    row.dataset.cls    = cls;
    row.dataset.type   = type;

    row.innerHTML = `
        <div class="pill ${pillCls}">${pillText}</div>
        <div class="dur ${durClass(cls)}">${elapsed ? elapsed.toFixed(4) + 's' : ''}</div>
        <div class="depth-col">${depth > 0 ? 'd' + depth : ''}</div>
        <div class="content">${contentHTML}</div>
    `;

    logEl.appendChild(row);

    // FIX 3: usar scrollTop del elemento, no window.scrollTo
    // window.scrollTo causaba saltos inesperados en algunos contextos embebidos
    logEl.parentElement.scrollTop = logEl.parentElement.scrollHeight;

    applyFilterToRow(row);
}

// ── filter ───────────────────────────────────────────────────────────────────

function applyFilterToRow(row) {
    const term     = fInput.value.toLowerCase();
    const onlySlow = chkSlow.checked;
    const onlyEnd  = chkEnd.checked;

    let visible = true;
    if (term && !row.dataset.search.includes(term)) visible = false;
    if (onlySlow && !['slow','vslow'].includes(row.dataset.cls)) visible = false;
    if (onlyEnd  && !['end','root_end'].includes(row.dataset.type)) visible = false;

    row.style.display = visible ? '' : 'none';
}

function applyFilter() {
    logEl.querySelectorAll('.line').forEach(applyFilterToRow);
}

// ── clear ────────────────────────────────────────────────────────────────────

async function clearTrace() {
    await fetch('/clear');
    cnt = 0; slow = 0; vslow = 0;
    cntEl.textContent = '0'; slEl.textContent = '0'; vslEl.textContent = '0'; lrEl.textContent = '—';
    logEl.innerHTML = '<div class="empty">Esperando eventos del servidor de trazas…</div>';
}

// ── connect ──────────────────────────────────────────────────────────────────

async function loadHistory() {
    const r = await fetch('/history');
    const history = await r.json();
    history.forEach(renderEvent);
}

loadHistory().then(() => {
    const source = new EventSource('/events');
    source.onmessage = e => renderEvent(JSON.parse(e.data));
    source.onerror   = () => {};   // reconexión automática del navegador
});
</script>
</body>
</html>"""

        self.send_response(200)
        self.send_header("Content-Type", "text/html; charset=utf-8")
        self.end_headers()
        self.wfile.write(html.encode("utf-8"))

    def _send_events(self):
        """Stream trace events to the browser using Server-Sent Events.

        Each connected browser receives its own queue. When the browser disconnects,
        the queue is removed from the active clients list.
        """

        client_queue = queue.Queue(maxsize=1000)

        with TRACE_LOCK:
            TRACE_CLIENTS.append(client_queue)

        self.send_response(200)
        self.send_header("Content-Type", "text/event-stream")
        self.send_header("Cache-Control", "no-cache")
        self.send_header("Connection", "keep-alive")
        self.end_headers()

        try:
            while True:
                event = client_queue.get()
                payload = json.dumps(event)
                self.wfile.write(f"data: {payload}\n\n".encode("utf-8"))
                self.wfile.flush()
        except (BrokenPipeError, ConnectionResetError):
            pass
        finally:
            with TRACE_LOCK:
                if client_queue in TRACE_CLIENTS:
                    TRACE_CLIENTS.remove(client_queue)


def start_trace_server(port=8079):
    """Start the local trace HTTP server once in a daemon thread.

    Args:
        port (int): TCP port where the dashboard will listen. Defaults to
            ``8079``.

    The function is idempotent: repeated calls return immediately once the
    server has already been started.
    """

    global SERVER_STARTED

    if SERVER_STARTED:
        return

    SERVER_STARTED = True

    def run():
        """Create and run the trace HTTP server loop.

        This function is executed inside a daemon thread so the dashboard can remain
        available without blocking the main Odoo process.
        """

        try:
            print(f"[PERF TRACE] Starting server on 0.0.0.0:{port}")
            server = TraceHTTPServer(("0.0.0.0", port), TraceRequestHandler)
            print(f"[PERF TRACE] Server started on 0.0.0.0:{port}")
            server.serve_forever()
        except Exception as error:
            print(f"[PERF TRACE] ERROR starting server: {error}")

    thread = threading.Thread(target=run, daemon=True)
    thread.start()
